In [1]:
import pandas as pd

In [77]:
df_errores= pd.read_csv('C:/data/tabla_errores.txt', sep='\t', encoding='latin1')
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CODIGO_ERROR       55 non-null     object
 1   DESCRIPCION_ERROR  64 non-null     object
 2   DETALLE            63 non-null     object
 3   SOLUCION           64 non-null     object
 4   SOLUCION 2         22 non-null     object
dtypes: object(5)
memory usage: 2.6+ KB

In [111]:
# Se carga el dataset en excel de Accidentes mortales
df_desgravamen= pd.read_excel('C:/data/446 - Desgravamen Desempleo - BBVA - P1.xlsx', sheet_name='Hoja1')

c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28398 is marked as a date but the serial value 19900831 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28399 is marked as a date but the serial value 19821005 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28400 is marked as a date but the serial value 19740903 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28401 is marked as a date but the serial value 19791018 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28402 is marked as a date but the serial value 19790903 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28403 is marked as a date but the serial value 19620410 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28404 is marked as a date but the serial value 19641118 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28405 is marked as a date but the serial value 19801203 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28406 is marked as a date but the serial value 19730822 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28407 is marked as a date but the serial value 19820622 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28408 is marked as a date but the serial value 19760527 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28409 is marked as a date but the serial value 19880802 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28410 is marked as a date but the serial value 19810417 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28411 is marked as a date but the serial value 19760619 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28412 is marked as a date but the serial value 19370429 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28413 is marked as a date but the serial value 19780807 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28414 is marked as a date but the serial value 19730429 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28415 is marked as a date but the serial value 19761211 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28416 is marked as a date but the serial value 19510717 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28417 is marked as a date but the serial value 19600404 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28418 is marked as a date but the serial value 19850303 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28419 is marked as a date but the serial value 19620723 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28420 is marked as a date but the serial value 19580227 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28421 is marked as a date but the serial value 19490907 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28422 is marked as a date but the serial value 19830520 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28423 is marked as a date but the serial value 19651220 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28424 is marked as a date but the serial value 19730920 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28425 is marked as a date but the serial value 19870903 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28426 is marked as a date but the serial value 19740814 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28427 is marked as a date but the serial value 19861127 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28428 is marked as a date but the serial value 19790612 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28429 is marked as a date but the serial value 19630621 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28430 is marked as a date but the serial value 19480223 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28431 is marked as a date but the serial value 19760929 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28432 is marked as a date but the serial value 19780807 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28433 is marked as a date but the serial value 19770615 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28434 is marked as a date but the serial value 19780206 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28435 is marked as a date but the serial value 19840127 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28436 is marked as a date but the serial value 19620629 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28437 is marked as a date but the serial value 19680813 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28438 is marked as a date but the serial value 19880806 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28439 is marked as a date but the serial value 19740304 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28440 is marked as a date but the serial value 19820207 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28441 is marked as a date but the serial value 19801001 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28442 is marked as a date but the serial value 19850820 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28443 is marked as a date but the serial value 19780809 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28444 is marked as a date but the serial value 19830721 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28445 is marked as a date but the serial value 19750112 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28446 is marked as a date but the serial value 19900727 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28447 is marked as a date but the serial value 19920916 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28448 is marked as a date but the serial value 19741011 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28449 is marked as a date but the serial value 19860921 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28450 is marked as a date but the serial value 19630923 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28451 is marked as a date but the serial value 19770720 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28452 is marked as a date but the serial value 19770906 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28453 is marked as a date but the serial value 19860520 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28454 is marked as a date but the serial value 19670718 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28455 is marked as a date but the serial value 19670718 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28456 is marked as a date but the serial value 19590109 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28457 is marked as a date but the serial value 19850701 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28458 is marked as a date but the serial value 19740311 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28459 is marked as a date but the serial value 19740211 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28460 is marked as a date but the serial value 19550330 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28461 is marked as a date but the serial value 19760512 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28462 is marked as a date but the serial value 19720910 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28463 is marked as a date but the serial value 19570621 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28464 is marked as a date but the serial value 19540625 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28465 is marked as a date but the serial value 19760504 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28466 is marked as a date but the serial value 19750910 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28467 is marked as a date but the serial value 19850514 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28468 is marked as a date but the serial value 19711121 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)
c:\Users\Nelvin Velazco\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\worksheet\_reader.py:223: UserWarning: Cell X28469 is marked as a date but the serial value 19530524 is outside the limits for dates. The cell will be treated as an error.
  warn(msg)

In [112]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50659 entries, 0 to 50658
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NRO LOTE                 50659 non-null  int64
 1   LOTES ANTERIORES         91 non-null     object
 2   FECHA CARGA              50659 non-null  object
 3   CODIGO PRODUCTO          48852 non-null  float64
 4   PRODUCTO                 48852 non-null  object
 5   CODIGO PLAN              48852 non-null  float64
 6   NOMBRE DE PLAN           48852 non-null  object
 7   COD DE CERTIFICADO       48852 non-null  float64
 8   FECINI_ALTA_CERTIFICADO  33562 non-null  object
 9   FECFIN_ALTA_CERTIFICADO  33562 non-null  object
 10  IDEDET                   50659 non-null  int64
 11  TIPO MOVIMIENTO          50659 non-null  object
 12  FEC. INICIO              50658 non-null  object
 13  FEC. FIN                 50658 non-null  object
 14  MONEDA                   50658 non-null  object
 15  SUMA ASEGURADA           50659 non-null  object
 16  TASA                     50659 non-null  object
 17  TASA RECARGO             50659 non-null  object
 18  PRIMABRUTACAN            50659 non-null  object
 19  PRIMANETACAN             50659 non-null  float64
 20  NOMCOMPLETO              50353 non-null  object
 21  APEPATERNO               50353 non-null  object
 22  APEMATERNO               50353 non-null  object
 23  FECNACIMIENTO            28293 non-null  object
 24  TIPDOCUMENTO             45279 non-null  float64
 25  NUMDOCUMENTO             50353 non-null  object
 26  NOMBRE DE ARCHIVO        50659 non-null  object
 27  IDELOTE                  50650 non-null  object
 28  IDEDET.1                 28833 non-null  float64
 29  ORIGEN ERROR             28833 non-null  float64
 30  CODIGO ERROR             28833 non-null  object
 31  DESCRIPCION ERROR        26946 non-null  float64
 32  Unnamed: 32              28833 non-null  object
dtypes: float64(8), int64(2), object(23)
memory usage: 12.8+ MB

In [113]:
df_desgravamen= df_desgravamen[['LOTES ANTERIORES','CODIGO PRODUCTO', 'COD DE CERTIFICADO', 'FECINI_ALTA_CERTIFICADO', 
                                'FECFIN_ALTA_CERTIFICADO','IDEDET', 'TIPO MOVIMIENTO', 'FEC. INICIO', 'FEC. FIN', 'MONEDA', 
                                'SUMA ASEGURADA', 'TASA', 'PRIMABRUTACAN', 'PRIMANETACAN', 'NOMBRE DE ARCHIVO', 
                                'ORIGEN ERROR', 'CODIGO ERROR', 'DESCRIPCION ERROR']]

In [114]:
df_desgravamen.head(3)  # Displaying the first five rows of the DataFrame

,LOTES ANTERIORES,CODIGO PRODUCTO,COD DE CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO MOVIMIENTO,FEC. INICIO,FEC. FIN,MONEDA,SUMA ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE DE ARCHIVO,ORIGEN ERROR,CODIGO ERROR,DESCRIPCION ERROR
0,41924|41960,3070.0,1.102912e+17,NaN,NaN,76792662,Renovacion,2015-03-26 00:00:00,2015-04-26 00:00:00,SOL,0,0,1.53,1.49,20100130204_0157001_20150409_001_41924.TXT,76792662.0,Error canal,1150.0
1,41924|41960,3070.0,1.102771e+17,NaN,NaN,76792295,Renovacion,2015-03-20 00:00:00,2015-04-20 00:00:00,SOL,0,0,13.13,12.75,20100130204_0157001_20150409_001_41924.TXT,76792295.0,Error canal,1150.0
2,41924|41960,3070.0,1.103549e+17,NaN,NaN,76795338,Renovacion,2015-03-12 00:00:00,2015-04-12 00:00:00,SOL,0,0,6.23,6.05,20100130204_0157001_20150409_001_41924.TXT,76795338.0,Error canal,1150.0

In [115]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50659 entries, 0 to 50658
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   LOTES ANTERIORES         91 non-null     object
 1   CODIGO PRODUCTO          48852 non-null  float64
 2   COD DE CERTIFICADO       48852 non-null  float64
 3   FECINI_ALTA_CERTIFICADO  33562 non-null  object
 4   FECFIN_ALTA_CERTIFICADO  33562 non-null  object
 5   IDEDET                   50659 non-null  int64
 6   TIPO MOVIMIENTO          50659 non-null  object
 7   FEC. INICIO              50658 non-null  object
 8   FEC. FIN                 50658 non-null  object
 9   MONEDA                   50658 non-null  object
 10  SUMA ASEGURADA           50659 non-null  object
 11  TASA                     50659 non-null  object
 12  PRIMABRUTACAN            50659 non-null  object
 13  PRIMANETACAN             50659 non-null  float64
 14  NOMBRE DE ARCHIVO        50659 non-null  object
 15  ORIGEN ERROR             28833 non-null  float64
 16  CODIGO ERROR             28833 non-null  object
 17  DESCRIPCION ERROR        26946 non-null  float64
dtypes: float64(5), int64(1), object(12)
memory usage: 7.0+ MB

In [102]:
df_desgravamen['IDELOTE'].value_counts()

IDELOTE
901001101476440002327130011014765960019828601PEN2LOMA                          LLANOS                        JUAN LORENZO                  MS19881107L45401826  MONTEVIDEO                                                                                                                        883     24      CERCADO DE LIMA               01L0001PERMJR.   010010019812751201502102015021020150511000C00000000500000{000000000001750 06I1 00035000000000000000000000000000000000000001750                                                                                                                                                                02    8
901001101633840001393030011016334960011024601PEN2AREVALO                       TERRONES                      HUMBERTO                      MC19660727L10463083  SAN PABLO                                                                                           SAN PABLO                     348             LA VICTORIA                   01L0013PERMAV.URB010130013241839201504152015041520150515000A00000001500000{000000000007650 03D1 00051000000000000000000000000000000000000007650                                                                                                                                                                02    8
901001100148140000207550011001484960001270701PEN2NUÑEZ                         WISSAR                        JOSE LUIS                     MS19711103L20721520  28 DE JULIO                                                                                                                       156             JAUJA                         13     PERMAV.   040110649540996201411262014112620150601000F00000000600000{000000000002100 06I1 00035000000000000000000000000000000000000002100                                                                                                                                                                02    8
901001101062740000855980011010626960008055901PEN2PILLACA                       GARAUNDO                      NELLY                         FC19721101L28288937  LA CAÑADA                                         ESPALDA DE VIVANDA MOLICENTRO                     RINCONADA ALTA                246             LA MOLINA                     01L0012PERMJR.URB010120019666043201503272015032720150511000B00000003100000{000000000010850 06I1 00035000000000000000000000000000000000000010850                                                                                                                                                                02    8
901001101021840002446860011010219960018608801PEN2RUIZ                          AGUILAR                       SOLEDAD                       FD19451025L25697541  DULIO POGGI                                       HAYA DE TORRE Y PACIFICO A MEDIA CDRA             TERCERA ETAPA ALTAMAR         649     3ERA.ETALA PERLA                      02C0004PERMCALETP010040014570194201502052015020520150605000D00000000015000{000000000000053 06I1 00035000000000000000000000000000000000000000053                                                                                                                                                                02    8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
901001103183840002696910011031831960028685001PEN2QUIROZ                        GALLARDO                      JESUS                         MS19751225L40090928  ALAMEDA PERU                                      *725197                                                                         122             RUPA RUPA                     11     PERMAV.   060040620564072201508112015021120150811000F00000000965000{000000000003378 06I1 00035000000000000000000000000000000000000003378                                                                                                                                                                02    1
901001103233940001860250011032338960011625101PEN2GONZALES                      VASQUEZ                       GENIO                         MS19880328L45372493  SN                                                ALT PARROQUIA SAN JOSE                            6 GRUPO 5                     MZ I    LT 17A  V. EL SALVADOR                01L0042PERMCALSEC010420019863742201508262015022720150827000F00000000010000{000000000000035 06I1 00035000000000000000000000000000000000000000035                                                                                                                                                                02    1
901001104827340000812100011048273960004399301PEN2MU#AQUI                       CAHUANA                       MICHAEL ALBERTO               MS19780604L40201012  PRECURSORES                                                                                         MARANGA                       698     102     SAN MIGUEL                    01L0032PERMAV.URB010320014646401201508312014123120151102003F00000001000000{000000000003500 06I1 00035000000000000000000000000000000000000003500                                                                                                                                                                02    1
901001101179640003096310011011798960029504001PEN2ROMAN                         SILVA                         CHRISTIAN                     MS19860727L43804549  DANIEL ALCIDEZ CARRION                                                                              JOSE GALVEZ                   1068            V.M. DEL TRIUNFO              01L0035PERMAV.URB010350012525020201508172015021320150817001B00000000010000{000000000000035 06I1 00035000000000000000000000000000000000000000035                                                                                                                                                                02    1
901001105543140000333570011055436020005305501PEN4                                                                                                                                                                                                                                                                                                         M                             20160610201607100000000000000000000000000000018303                                                                                                                                                                                                                     02    1
Name: count, Length: 43614, dtype: int64

In [116]:
def limpiar_codigo_error(x):
    if pd.isnull(x):
        return ''
    try:
        # Si es un número tipo float, conviértelo a int y luego a str
        return str(int(x))
    except:
        # Si no se puede convertir, déjalo como str tal cual
        return str(x)

In [117]:
df_desgravamen['CODIGO ERROR'] = df_desgravamen['CODIGO ERROR'].apply(limpiar_codigo_error)

In [118]:
df_desgravamen['CODIGO ERROR'].value_counts()

CODIGO ERROR
               21826
Error canal    15461
Error Rimac    13372
Name: count, dtype: int64

In [ ]:
df_desgravamen['COD DE CERTIFICADO'] = df_desgravamen['COD DE CERTIFICADO'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
df_desgravamen['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECINI_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_desgravamen['FECFIN_ALTA_CERTIFICADO'], errors='coerce')
df_desgravamen['TIPO MOVIMIENTO'] = df_desgravamen['TIPO MOVIMIENTO'].astype(str)
df_desgravamen['FEC. INICIO'] = pd.to_datetime(df_desgravamen['FEC. INICIO'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['FEC. FIN'] = pd.to_datetime(df_desgravamen['FEC. FIN'], format='%d/%m/%Y', errors='coerce')
df_desgravamen['MONEDA'] = df_desgravamen['MONEDA'].astype(str)
df_desgravamen['SUMA ASEGURADA']= pd.to_numeric(df_desgravamen['SUMA ASEGURADA'], errors='coerce')
df_desgravamen['TASA']= pd.to_numeric(df_desgravamen['TASA'], errors='coerce')
df_desgravamen['PRIMABRUTACAN']= pd.to_numeric(df_desgravamen['PRIMABRUTACAN'], errors='coerce')
df_desgravamen['PRIMANETACAN']= pd.to_numeric(df_desgravamen['PRIMANETACAN'], errors='coerce')
df_desgravamen['ORIGEN ERROR'] = df_desgravamen['ORIGEN ERROR'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
#df_desgravamen['CODIGO ERROR'] = df_desgravamen['CODIGO ERROR'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')
df_desgravamen['DESCRIPCION ERROR'] = df_desgravamen['DESCRIPCION ERROR'].apply(lambda x: str(int(x)) if pd.notnull(x) else '0')

ValueError: invalid literal for int() with base 10: 'Error canal'

In [69]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50659 entries, 0 to 50658
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO PRODUCTO          48852 non-null  float64
 1   COD DE CERTIFICADO       50659 non-null  object
 2   FECINI_ALTA_CERTIFICADO  33562 non-null  datetime64[ns]
 3   FECFIN_ALTA_CERTIFICADO  33562 non-null  datetime64[ns]
 4   IDEDET                   50659 non-null  int64
 5   TIPO MOVIMIENTO          50659 non-null  object
 6   FEC. INICIO              50142 non-null  datetime64[ns]
 7   FEC. FIN                 50142 non-null  datetime64[ns]
 8   MONEDA                   50659 non-null  object
 9   SUMA ASEGURADA           50146 non-null  float64
 10  TASA                     50657 non-null  float64
 11  PRIMABRUTACAN            50151 non-null  float64
 12  PRIMANETACAN             50659 non-null  float64
 13  NOMBRE DE ARCHIVO        50659 non-null  object
 14  IDELOTE                  50659 non-null  object
 15  ORIGEN ERROR             50659 non-null  object
 16  CODIGO ERROR             50659 non-null  object
 17  DESCRIPCION ERROR        50659 non-null  object
dtypes: datetime64[ns](4), float64(5), int64(1), object(8)
memory usage: 7.0+ MB

In [70]:
df_desgravamen.head(5)

,CODIGO PRODUCTO,COD DE CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO MOVIMIENTO,FEC. INICIO,FEC. FIN,MONEDA,SUMA ASEGURADA,TASA,PRIMABRUTACAN,PRIMANETACAN,NOMBRE DE ARCHIVO,IDELOTE,ORIGEN ERROR,CODIGO ERROR,DESCRIPCION ERROR
0,3070.0,110291214000143008,NaT,NaT,76792662,Renovacion,2015-03-26,2015-04-26,SOL,0.0,0.0,1.53,1.49,20100130204_0157001_20150409_001_41924.TXT,901001102912140001431290011029122020009653701P...,76792662.0,Error canal,Error canal
1,3070.0,110277104000246000,NaT,NaT,76792295,Renovacion,2015-03-20,2015-04-20,SOL,0.0,0.0,13.13,12.75,20100130204_0157001_20150409_001_41924.TXT,901001102771040002469910011027719020027608301P...,76792295.0,Error canal,Error canal
2,3070.0,110354884000092000,NaT,NaT,76795338,Renovacion,2015-03-12,2015-04-12,SOL,0.0,0.0,6.23,6.05,20100130204_0157001_20150409_001_41924.TXT,901001103548840000928950011035489020035748001P...,76795338.0,Error canal,Error canal
3,3070.0,110195594000396992,NaT,NaT,76787274,Renovacion,2015-03-18,2015-04-18,SOL,0.0,0.0,0.44,0.43,20100130204_0157001_20150409_001_41924.TXT,901001101955940003973820011019550020010881901P...,76787274.0,Error canal,Error canal
4,3827.0,110960264000002000,NaT,NaT,142143999,Renovacion,2016-06-06,2016-07-06,USD,0.0,0.0,8.99,8.73,20100130204_0157001_20160706_002.TXT,901001109602640000029710011040826020022755501U...,142143999.0,Error canal,Error canal

In [75]:
df_desgravamen= df_desgravamen.fillna({'CODIGO PRODUCTO':0, 'SUMA ASEGURADA':0, 'TASA':0, 'PRIMABRUTACAN':0, 'PRIMANETACAN':0})

In [76]:
df_desgravamen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50659 entries, 0 to 50658
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   CODIGO PRODUCTO          50659 non-null  float64
 1   COD DE CERTIFICADO       50659 non-null  object
 2   FECINI_ALTA_CERTIFICADO  33562 non-null  datetime64[ns]
 3   FECFIN_ALTA_CERTIFICADO  33562 non-null  datetime64[ns]
 4   IDEDET                   50659 non-null  int64
 5   TIPO MOVIMIENTO          50659 non-null  object
 6   FEC. INICIO              50142 non-null  datetime64[ns]
 7   FEC. FIN                 50142 non-null  datetime64[ns]
 8   MONEDA                   50659 non-null  object
 9   SUMA ASEGURADA           50659 non-null  float64
 10  TASA                     50659 non-null  float64
 11  PRIMABRUTACAN            50659 non-null  float64
 12  PRIMANETACAN             50659 non-null  float64
 13  NOMBRE DE ARCHIVO        50659 non-null  object
 14  IDELOTE                  50659 non-null  object
 15  ORIGEN ERROR             50659 non-null  object
 16  CODIGO ERROR             50659 non-null  object
 17  DESCRIPCION ERROR        50659 non-null  object
dtypes: datetime64[ns](4), float64(5), int64(1), object(8)
memory usage: 7.0+ MB

In [78]:
df_errores.head()

,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION 2
0,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN
2,1155,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS
3,1150,ERROR EN ALTA,EL ALTA DEL NRO. CERTIFICADO EXTERNO SE ENCUEN...,ANALISIS EMISOR,NaN
4,1152,ERROR EN ALTA,NO EXISTE ALTA PARA EL CERTIFICADO O TIENE BAJ...,ANALISIS EMISOR,NaN

---

In [71]:
df_desgravamen[df_desgravamen['FECINI_ALTA_CERTIFICADO'].isnull()]['FECINI_ALTA_CERTIFICADO'].isnull().value_counts()

FECINI_ALTA_CERTIFICADO
True    17097
Name: count, dtype: int64

In [72]:
#TIPO MOVIMIENTO
df_desgravamen['FECINI_ALTA_CERTIFICADO'].value_counts()  # Counting occurrences of each unique value in the 'TIPO MOVIMIENTO' column

FECINI_ALTA_CERTIFICADO
2015-03-31    134
2014-12-30    124
2015-05-29    114
2015-10-30    106
2015-07-31    105
             ...
2012-08-23      1
2013-01-08      1
2013-05-08      1
2013-03-11      1
2017-01-15      1
Name: count, Length: 1161, dtype: int64

In [28]:
#MONEDA
df_desgravamen['MONEDA'].value_counts()  # Counting occurrences of each unique value in the 'MONEDA' column

MONEDA
SOL    46356
USD     4302
Name: count, dtype: int64

In [73]:
df_desgravamen[df_desgravamen['SUMA ASEGURADA'].isnull()]['SUMA ASEGURADA'].isnull().value_counts()

SUMA ASEGURADA
True    513
Name: count, dtype: int64