In [2]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import unicodedata
import os
pd.set_option('display.max_columns', None)

In [3]:
espacios_col = [(0, 3), (3, 23), (23, 43), (43,45), (45, 48), (48, 49), (49, 79), (79, 109), (109, 139),   
                (139, 140), (140, 141), (141, 149), (149, 150), (150, 160), (160, 210), (210, 235),   
                (235, 260), (260, 290), (290, 298), (298, 306), (306, 336), (336, 338), (338, 343),   
                (343, 346), (346, 347), (347, 350), (350, 353), (353, 355), (355, 358), (358, 361), 
                (361, 368), (368, 376), (376, 384), (384, 392), (392, 396), (396, 411), (411, 426),   
                (426, 427), (427, 429), (429, 430), (430, 431), (431, 432), (432, 442), (442, 449),   
                (449, 522), (522, 524), (524, 527), (527, 530), (530, 540), (540, 550), (550,565),
                (565, 635), (635, 637), (637, 639), (639,641)]

column_names = ["Tipo de seguro", "Certificado", "Numero Interno Del Canal", "Tipo de Registro", "Moneda", 
                "Tipo de Movimiento", "Apellido Paterno", "Apellido Materno", "Nombres", "Sexo", "Estado Civil", 
                "Fecha de Nacimiento", "Tipo de Documento de Identidad", "Numero de Documento de Identidad", 
                "Dirección Domiciliaria", "Referencia", "Referencia2", "Urbanización", "Mz/Lte/Nro", "Apto/Int", 
                "Distrito", "Departamento", "Código Postal", "País", "Periodo de pago", "Prefijo Calle,Av,Jr", 
                "Prefijo 2", "Provincia", "Distrito2", "Prefijo Teléfono", "Numero Teléfono", "Fecha de Afiliación", 
                "Fecha de inicio del seguro", "Fecha fin del seguro", "Plazo del seguro", "Monto Asegurado", "Prima", 
                "Período de Gracia", "Código de Beneficiario", "Clase de Prima", "Tipo de Titular", "Mayor a 65 Años", 
                "Tasa sin Recargo", "% de recargo", "Filler", "Tiempo de Periodo de Gracia", "Tipos de Endoso", 
                "Tipos de Extorno", "Tipo de cambio", "Póliza", "Sumatoria de Capital en Cúmulo", "Correo electrónico", 
                "Plan de crédito", "Planes Tipo Desgravamen", "Planes de Seguro (o Modalidad)"
                ]

In [115]:
excel_file = pd.ExcelFile('C:/data/02. REPORTE TC/06. JUNIO/TC - DECLARADO.xlsx')
print(excel_file.sheet_names)

['ESTRUCTURA', 'Hoja1', 'TRAMAS', 'TABLA']

In [117]:
df_declarado= pd.read_excel('C:/data/02. REPORTE TC/06. JUNIO/TC - DECLARADO.xlsx', sheet_name='TRAMAS', dtype={'Certificado ': str})

In [118]:
df_declarado.head(3)

,TRAMA,Tipo de seguro,Certificado,Numero Interno Del Canal,Tipo de Registro,Moneda,Tipo de Movimiento,Apellido Paterno,Apellido Materno,Nombres,Sexo,Estado Civil,Fecha de Nacimiento,Tipo de Documento de Identidad,Numero de Documento de Identidad,Dirección Domiciliaria,Referencia,Referencia2,Urbanización,Mz/Lte/Nro,Apto/Int,Distrito,Departamento,Código Postal,País,Periodo de pago,"Prefijo Calle,Av,Jr",Prefijo 2,Provincia,Distrito.1,Prefijo Teléfono,Numero Teléfono,Fecha de Afiliación,Fecha de inicio del seguro,Fecha fin del seguro,Plazo del seguro,Monto Asegurado,Prima,Período de Gracia,Código de Beneficiario,Clase de Prima,Tipo de Titular,Filler,Tasa sin Recargo,% de recargo,Prima Desempleo / Retorno,Prima Desgravamen,Tipo_Bin,Multi_Bin,Filler.1,Correo electrónico,Nro. Poliza,Planes Tipo Desgravamen,Planes de Seguro (o Modalidad),MONTO ASEGURADO,PRIMA,PDOL
0,918001100536440002282350011050489500143960101P...,918.0,00110053644000228235,1.105049e+17,1.0,PEN,4.0,PAYPAY,SANCHEZ,LISHNER YANCARLOS,M,S,19901013.0,L,46605250.0,NO APLICA ...,,,NO APLICA,,,,,,,,NA,NA,,,93.0,8137903.0,20250512.0,20250410.0,20250509.0,099I,00000000055107E,00000000000187D,,6.0,I,1.0,,3400000.0,0.0,00000000000000{,00000000000187D,404293.0,,...,...,,,1.0,5510.75,18.74,5.17
1,918001101518240003183260011050480500205954301P...,918.0,00110151824000318326,1.105048e+17,1.0,PEN,4.0,COELLO,GUERRA,EDWIN FELIPE,M,S,19891221.0,L,46124490.0,NO APLICA ...,,,NO APLICA,,,,,,,,NA,NA,,,95.0,5949334.0,20250512.0,20250410.0,20250509.0,099I,00000000047756A,00000000000162D,,6.0,I,1.0,,3400000.0,0.0,00000000000000{,00000000000162D,414791.0,,...,...,,,1.0,4775.61,16.24,4.48
2,918001104082140043559900011040823500961584901P...,918.0,00110408214004355990,1.104082e+17,1.0,PEN,4.0,CALDERON,FELIX,YAN FRANCO,M,S,19901112.0,L,70438996.0,APURIMAC ...,ESPALDA DEL HOTEL D,,NO APLICA,508,,ABANCAY,05,,PER,,JR.,NA,01,001,98.0,6825234.0,20250512.0,20250410.0,20250509.0,099I,00000000006438I,00000000000021I,,6.0,I,1.0,,3400000.0,0.0,00000000000000{,00000000000021I,491914.0,,...,...,,,1.0,643.89,2.19,0.60

In [119]:
df_declarado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 695740 entries, 0 to 695739
Data columns (total 57 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   TRAMA                             695740 non-null  object
 1   Tipo de seguro                    5 non-null       float64
 2   Certificado                       695740 non-null  object
 3   Numero Interno Del Canal          5 non-null       float64
 4   Tipo de Registro                  5 non-null       float64
 5   Moneda                            695740 non-null  object
 6   Tipo de Movimiento                5 non-null       float64
 7   Apellido Paterno                  5 non-null       object
 8   Apellido Materno                  5 non-null       object
 9   Nombres                           5 non-null       object
 10  Sexo                              5 non-null       object
 11  Estado Civil                      5 non-null       object
 12  Fecha de Nacimiento               5 non-null       float64
 13  Tipo de Documento de Identidad    5 non-null       object
 14  Numero de Documento de Identidad  5 non-null       float64
 15  Dirección Domiciliaria            5 non-null       object
 16  Referencia                        5 non-null       object
 17  Referencia2                       5 non-null       object
 18  Urbanización                      5 non-null       object
 19  Mz/Lte/Nro                        5 non-null       object
 20  Apto/Int                          5 non-null       object
 21  Distrito                          5 non-null       object
 22  Departamento                      5 non-null       object
 23  Código Postal                     5 non-null       object
 24  País                              5 non-null       object
 25  Periodo de pago                   5 non-null       object
 26  Prefijo Calle,Av,Jr               5 non-null       object
 27  Prefijo 2                         5 non-null       object
 28  Provincia                         5 non-null       object
 29  Distrito.1                        5 non-null       object
 30  Prefijo Teléfono                  5 non-null       float64
 31  Numero Teléfono                   5 non-null       float64
 32  Fecha de Afiliación               5 non-null       float64
 33  Fecha de inicio del seguro        5 non-null       float64
 34  Fecha fin del seguro              5 non-null       float64
 35  Plazo del seguro                  5 non-null       object
 36  Monto Asegurado                   695740 non-null  object
 37  Prima                             695740 non-null  object
 38  Período de Gracia                 5 non-null       object
 39  Código de Beneficiario            5 non-null       float64
 40  Clase de Prima                    5 non-null       object
 41  Tipo de Titular                   5 non-null       float64
 42  Filler                            5 non-null       object
 43  Tasa sin Recargo                  5 non-null       float64
 44  % de recargo                      5 non-null       float64
 45  Prima Desempleo / Retorno         5 non-null       object
 46  Prima Desgravamen                 5 non-null       object
 47  Tipo_Bin                          5 non-null       float64
 48  Multi_Bin                         5 non-null       object
 49  Filler.1                          5 non-null       object
 50  Correo electrónico                5 non-null       object
 51  Nro. Poliza                       5 non-null       object
 52  Planes Tipo Desgravamen           5 non-null       object
 53  Planes de Seguro (o Modalidad)    5 non-null       float64
 54  MONTO ASEGURADO                   695730 non-null  float64
 55  PRIMA                             695740 non-null  float64
 56  PDOL                              695740 non-null  float64
dtypes: float64(20), object(37)
memory usage: 302.6+ MB

In [120]:
df_declarado= df_declarado[['TRAMA','Certificado ']]

In [121]:
df_declarado.head(3)

                                               TRAMA          Certificado
0  918001100536440002282350011050489500143960101P...  00110053644000228235
1  918001101518240003183260011050480500205954301P...  00110151824000318326
2  918001104082140043559900011040823500961584901P...  00110408214004355990

In [122]:
df_declarado['Certificado '].value_counts()

Certificado
00110053644000228235    1
00110151824000318326    1
00110408214004355990    1
00110408214004685575    1
00110281364000741498    1
                       ..
00110324114001007197    1
00110324144001145220    1
00110504844002158669    1
00110785374002474888    1
00110504884002285873    1
Name: count, Length: 695740, dtype: int64

In [123]:
df_declarado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 695740 entries, 0 to 695739
Data columns (total 2 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   TRAMA         695740 non-null  object
 1   Certificado   695740 non-null  object
dtypes: object(2)
memory usage: 10.6+ MB

In [125]:
excel_file = pd.ExcelFile('C:/data/02. REPORTE TC/06. JUNIO/TC - SAS.xlsx')
print(excel_file.sheet_names)

['Hoja1', 'EMI - TC 23.06_86691 (2)']

In [126]:
df_Emitidos= pd.read_excel('C:/data/02. REPORTE TC/06. JUNIO/TC - SAS.xlsx', sheet_name= 'EMI - TC 23.06_86691 (2)')#, skiprows=7)

In [127]:
df_Emitidos.head(3)

,NRO LOTE,TIPO,NRO LOTES ANTERIORES,FECHA CARGA LOTE,CÓDIGO PRODUCTO,PRODUCTO,PLAN,NOMBRE DE PLAN,CÓD. CERTIFICADO CANAL,TIPO MOVIMIENTO,NOMBRE,APELLIDO PATERNO,APELLIDO MATERNO,FECHA NACIMIENTO,TIPO DOC. ID,DOC. ID.,FEC. INICIO,FEC. FIN,MONEDA,SUMA ASEGURADA,TASA,TASA CON RECARGO,PRIMABRUTACAN,PRIMANETACAN,PLACA,MOTOR,NOMBRE ARCHIVO,LÍNEA DE TRAMA,LINEA TRAMA(TEXTO COMPLETO),ESTADO,DESCRIPCIÓN DE ESTADO,CÓDIGO DE RAMO,CÓDIGO DE PRODUCTO EN CORE,MONEDA.1,PRIMA NETA,DERECHO DE EMISIÓN,IGV,INTERES FINANCIAMIENTO,IGV INTERES_FINANCIAMIENTO,OTROS CONCEPTOS,PRIMA BRUTA,DUPLICADOS,PDOLS,COMISION,NUMERO CERTIFICADO RIMAC,NUMERO DE POLIZA,TIPO DOC EMISIÓN,N. DOC EMISIÓN,FECHA DE EMISIÓN,CONTRATANTE,RESPONSABLE DE PAGO,ESTADO DE DOCUMENTO,IDEREGISTRO,NUMERO DE POLIZA AE,FEC. INICIO AE,FEC. FIN AE,PRIMA BRUTA AE,MONTO COMISIÓN CANAL,FEC. INICIO AX,FEC. FIN AX,PRIMA BRUTA AX,TIPO DOC EMISIÓN ORIGEN,N. DOC EMISIÓN ORIGEN
0,1250339,REGULARIZACION,NaN,2024-11-08 15:33:10,4046,Desgravamen BBVA - T. Credito + Desempleo,378370,Plan Premier Saldo insoluto soles,C00110014884000446000,Renovacion,CESAR RAUL,YARINGA#O,CASTA#EDA,1972-09-19,2,20043471,2024-09-20,2024-10-18,SOL,158.74,0.256,0.256,0.41,0.40,NaN,NaN,20100130204_0158001_20241101_004.TXT,3678,918001100148840004460000011001487500044830101P...,Terminado,Emitido en A/X,VTHD,158.0,SOL,0.4,0.01,0,0,0,0,0.41,NaN,0.11,0,'15801978740-1,'8793500001,LQ,1709721932,2025-06-16 00:00:00,BANCO BBVA PERU,CESAR RAUL YARINGA#O CASTA#EDA,COB,720333897,8793500001,2024-08-22,2071-09-18,0.41,0.3,NaN,NaN,NaN,NaN,NaN
1,1250339,REGULARIZACION,NaN,2024-11-08 15:33:10,4046,Desgravamen BBVA - T. Credito + Desempleo,378370,Plan Premier Saldo insoluto soles,C00110014874000434371,Renovacion,FREDY,QUISPE,CORDOVA,1979-01-17,2,40230848,2024-09-10,2024-10-10,SOL,94.28,0.256,0.256,0.24,0.23,NaN,NaN,20100130204_0158001_20241101_004.TXT,3604,918001100148740004343710011001482500043403301P...,Terminado,Emitido en A/X,VTHD,158.0,SOL,0.23,0.01,0,0,0,0,0.24,NaN,0.07,0,'15801866718-1,'8793500001,LQ,1709723595,2025-06-16 00:00:00,BANCO BBVA PERU,FREDY QUISPE CORDOVA,COB,720333823,8793500001,2024-04-30,2078-01-16,0.24,0.17,NaN,NaN,NaN,NaN,NaN
2,1250339,REGULARIZACION,NaN,2024-11-08 15:33:10,4046,Desgravamen BBVA - T. Credito + Desempleo,378370,Plan Premier Saldo insoluto soles,C00110124584000291102,Renovacion,SEGUNDO JOSE ANTONIO,ESTELA,VASQUEZ,1984-02-12,2,42334877,2024-09-10,2024-10-10,SOL,1000.09,0.256,0.256,2.56,2.49,NaN,NaN,20100130204_0158001_20241101_004.TXT,47407,918001101245840002911020011050480500254102701P...,Terminado,Emitido en A/X,VTHD,158.0,SOL,2.49,0.07,0,0,0,0,2.56,NaN,0.71,0,'15801330597-1,'8793500001,LQ,1709723555,2025-06-16 00:00:00,BANCO BBVA PERU,SEGUNDO JOSE ANTONIO ESTELA VASQUEZ,COB,720377628,8793500001,2022-07-24,2069-02-11,2.56,1.84,NaN,NaN,NaN,NaN,NaN

In [128]:
df_Emitidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615276 entries, 0 to 615275
Data columns (total 63 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   NRO LOTE                     615276 non-null  int64
 1   TIPO                         615276 non-null  object
 2   NRO LOTES ANTERIORES         86 non-null      object
 3   FECHA CARGA LOTE             615276 non-null  datetime64[ns]
 4   CÓDIGO PRODUCTO              615276 non-null  int64
 5   PRODUCTO                     615276 non-null  object
 6   PLAN                         615276 non-null  int64
 7   NOMBRE DE PLAN               615276 non-null  object
 8   CÓD. CERTIFICADO CANAL       615276 non-null  object
 9   TIPO MOVIMIENTO              615276 non-null  object
 10  NOMBRE                       615276 non-null  object
 11  APELLIDO PATERNO             615276 non-null  object
 12  APELLIDO MATERNO             615275 non-null  object
 13  FECHA NACIMIENTO             615276 non-null  datetime64[ns]
 14  TIPO DOC. ID                 615276 non-null  int64
 15  DOC. ID.                     615276 non-null  object
 16  FEC. INICIO                  615276 non-null  datetime64[ns]
 17  FEC. FIN                     615276 non-null  datetime64[ns]
 18  MONEDA                       615276 non-null  object
 19  SUMA ASEGURADA               615276 non-null  float64
 20  TASA                         615276 non-null  float64
 21  TASA CON RECARGO             615276 non-null  float64
 22  PRIMABRUTACAN                615276 non-null  float64
 23  PRIMANETACAN                 615276 non-null  float64
 24  PLACA                        0 non-null       float64
 25  MOTOR                        0 non-null       float64
 26  NOMBRE ARCHIVO               615276 non-null  object
 27  LÍNEA DE TRAMA               615276 non-null  int64
 28  LINEA TRAMA(TEXTO COMPLETO)  615276 non-null  object
 29  ESTADO                       615276 non-null  object
 30  DESCRIPCIÓN DE ESTADO        615276 non-null  object
 31  CÓDIGO DE RAMO               614650 non-null  object
 32  CÓDIGO DE PRODUCTO EN CORE   614650 non-null  float64
 33  MONEDA.1                     614650 non-null  object
 34  PRIMA NETA                   614650 non-null  object
 35  DERECHO DE EMISIÓN           614650 non-null  object
 36  IGV                          614650 non-null  object
 37  INTERES FINANCIAMIENTO       614650 non-null  object
 38  IGV INTERES_FINANCIAMIENTO   614650 non-null  object
 39  OTROS CONCEPTOS              614650 non-null  object
 40  PRIMA BRUTA                  614650 non-null  float64
 41  DUPLICADOS                   43175 non-null   float64
 42  PDOLS                        615276 non-null  float64
 43  COMISION                     614650 non-null  object
 44  NUMERO CERTIFICADO RIMAC     615276 non-null  object
 45  NUMERO DE POLIZA             615276 non-null  object
 46  TIPO DOC EMISIÓN             614650 non-null  object
 47  N. DOC EMISIÓN               614650 non-null  object
 48  FECHA DE EMISIÓN             614650 non-null  object
 49  CONTRATANTE                  614650 non-null  object
 50  RESPONSABLE DE PAGO          614650 non-null  object
 51  ESTADO DE DOCUMENTO          615276 non-null  object
 52  IDEREGISTRO                  615276 non-null  int64
 53  NUMERO DE POLIZA AE          615276 non-null  int64
 54  FEC. INICIO AE               615276 non-null  datetime64[ns]
 55  FEC. FIN AE                  615276 non-null  datetime64[ns]
 56  PRIMA BRUTA AE               615276 non-null  float64
 57  MONTO COMISIÓN CANAL         614650 non-null  object
 58  FEC. INICIO AX               0 non-null       float64
 59  FEC. FIN AX                  0 non-null       float64
 60  PRIMA BRUTA AX               0 non-null       float64
 61  TIPO DOC EMISIÓN ORIGEN      0 non-null       float64
 62  N. DOC EMISIÓN ORIGEN        0 non-null       float64
dtypes: datetime64[ns](6), float64(17), int64(7), object(33)
memory usage: 295.7+ MB

In [129]:
df_Emitidos['Certificado'] = df_Emitidos['CÓD. CERTIFICADO CANAL'].str[1:]
df_Emitidos= df_Emitidos[['Certificado','NRO LOTE']]

In [130]:
df_Emitidos.head(3)

            Certificado  NRO LOTE
0  00110014884000446000   1250339
1  00110014874000434371   1250339
2  00110124584000291102   1250339

In [131]:
df_Emitidos['Certificado'].value_counts()

Certificado
00110164144000533546    2
00110129454000722283    2
00110153414000621356    2
00110318344001021154    2
00110135114001272101    2
                       ..
00110408204006015526    1
00110408204006070829    1
00110408204006115601    1
00110408204006144830    1
00110114624000400632    1
Name: count, Length: 615242, dtype: int64

In [132]:
df_declarado.rename(columns={'Certificado ': 'Certificado'}, inplace=True)

In [133]:
df_cruce= pd.merge(df_declarado, df_Emitidos, how='left', on='Certificado')

In [134]:
df_cruce.head(3)

,TRAMA,Certificado,NRO LOTE
0,918001100536440002282350011050489500143960101P...,00110053644000228235,1312912.0
1,918001101518240003183260011050480500205954301P...,00110151824000318326,1312912.0
2,918001104082140043559900011040823500961584901P...,00110408214004355990,1312912.0

In [135]:
df_cruce['Certificado'].value_counts()

Certificado
00110314234001091010    2
00110153414000621356    2
00110142764000563518    2
00110139304000672450    2
00110115334000964744    2
                       ..
00110233404001333510    1
00110261584000369271    1
00110306894002348356    1
00110306884002365412    1
00110306874002454423    1
Name: count, Length: 695740, dtype: int64

In [136]:
df_cruce['NRO LOTE'].isna().value_counts()

NRO LOTE
False    614433
True      81330
Name: count, dtype: int64

In [137]:
df_cruce['EMITIDO'] = df_cruce['NRO LOTE'].notnull()

In [138]:
df_cruce['EMITIDO'].value_counts()

EMITIDO
True     614433
False     81330
Name: count, dtype: int64

In [139]:
df_cruce.drop('NRO LOTE', axis=1, inplace=True)

In [140]:
df_cruce.rename(columns={'TRAMA': 'Trama_Original'}, inplace=True)

In [141]:
df_cruce.head(3)

,Trama_Original,Certificado,EMITIDO
0,918001100536440002282350011050489500143960101P...,00110053644000228235,True
1,918001101518240003183260011050480500205954301P...,00110151824000318326,True
2,918001104082140043559900011040823500961584901P...,00110408214004355990,True

In [142]:
df_cruce[df_cruce['EMITIDO']==False].head(3)

,Trama_Original,Certificado,EMITIDO
43,918001107853240020754010011078535500367840801P...,00110785324002075401,False
210,918001103530240003008830011035302500189152001P...,00110353024000300883,False
335,918001101625740001896900011083155500150822901P...,00110162574000189690,False

In [143]:
df_cruce.to_excel('c:/data/cruce_TC_Junio.xlsx', index=False)

###############################################################################################

In [63]:
df_desgravamen= pd.read_excel('C:/data/01. ENERO - LIQUIDACIONES - TC.xlsx', sheet_name=None)

In [65]:
print(df_desgravamen.keys())

dict_keys(['Hoja2', 'Hoja1'])

In [68]:
df_liquidaciones= df_desgravamen['Hoja1'].copy()

In [69]:
df_liquidaciones.head()

,Desc Canal,Cod Prod,Producto,TipoDoc,NumDoc,Monto,Moneda,Fecha Emisión,Fecha. Inicio Vigencia,Fecha Fin Vigencia,Fecha Vencimiento,Fecha Anulación,Estado,Cert Externo,Nro Póliza RIMAC,Nro Certificado RIMAC,Codigo Usuario,Nombre Usuario
0,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671618136,18.68,SOL,2025-01-23,2024-11-08,2024-12-26,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
1,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671618941,0.45,SOL,2025-01-23,2024-11-08,2024-12-08,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
2,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671620580,13.01,SOL,2025-01-23,2024-11-08,2024-12-17,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
3,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671618135,2.86,SOL,2025-01-23,2024-11-08,2024-12-08,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI
4,BANCO BBVA PERU,8763,DESGRAVAMEN TC BBVA CREDITO,LQ,1671620582,19.03,SOL,2025-01-23,2024-11-08,2024-12-10,2024-11-08,NaT,COB,',NaN,NaN,DT_CULQI,DT_CULQI

In [70]:
df_liquidaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 619007 entries, 0 to 619006
Data columns (total 18 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Desc Canal              619007 non-null  object
 1   Cod Prod                619007 non-null  int64
 2   Producto                619007 non-null  object
 3   TipoDoc                 619007 non-null  object
 4   NumDoc                  619007 non-null  int64
 5   Monto                   619007 non-null  float64
 6   Moneda                  619007 non-null  object
 7   Fecha Emisión           619007 non-null  datetime64[ns]
 8   Fecha. Inicio Vigencia  619007 non-null  datetime64[ns]
 9   Fecha Fin Vigencia      619007 non-null  datetime64[ns]
 10  Fecha Vencimiento       619007 non-null  datetime64[ns]
 11  Fecha Anulación         28 non-null      datetime64[ns]
 12  Estado                  619007 non-null  object
 13  Cert Externo            619007 non-null  object
 14  Nro Póliza RIMAC        0 non-null       float64
 15  Nro Certificado RIMAC   0 non-null       float64
 16  Codigo Usuario          619007 non-null  object
 17  Nombre Usuario          619007 non-null  object
dtypes: datetime64[ns](5), float64(3), int64(2), object(8)
memory usage: 85.0+ MB

In [76]:
df_liquidaciones['Moneda'].value_counts()

Moneda
SOL    618338
USD       669
Name: count, dtype: int64