In [1]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import os
import numpy as np
pd.set_option('display.max_columns', None)

In [25]:
excel_file1 = pd.ExcelFile('C:/data/Data Errores/DATA_ERRORES_29_agos.xlsx')
excel_file2 = pd.ExcelFile('C:/data/Data Errores/DATA_ERRORES_02_sept.xlsx')
print(excel_file1.sheet_names)
print(excel_file2.sheet_names)

['GENERAL', 'TABLA ERROR']
['Hoja1']

In [36]:
df_Certificados1 = pd.read_excel('C:/data/Data Errores/DATA_ERRORES_29_agos.xlsx', sheet_name='GENERAL', dtype={'NUMCERTIFICADOEXT': str, 'IDEERROR': str})
df_Certificados2 = pd.read_excel('C:/data/Data Errores/DATA_ERRORES_02_sept.xlsx', sheet_name='Hoja1', dtype={'NUMCERTIFICADOEXT': str, 'IDEERROR': str})

In [37]:
df_Certificados1.head(3)

,CODIGOTEMP,IDELOTE,IDEDET,NUMCERTIFICADOEXT,ESTADO,MES,ANIO,IDEERROR,FECINIVIGCAN,FECFINVIGCAN,TIENE_PRO,ULTIMA_FECHA_PRO
0,REGBBVAMATRIZ290825,1072121,640961814,00110002304000164476,ERR,10,2023,2046,2023-10-02,2023-10-31,8,2023-09-30
1,REGBBVAMATRIZ290825,1143995,674735231,00110002304000183861,ERR,2,2024,2048,2024-02-26,2024-04-01,0,NaT
2,REGBBVAMATRIZ290825,1143995,674735231,00110002304000183861,ERR,2,2024,1153,2024-02-26,2024-04-01,0,NaT

In [38]:
df_Certificados2.head(3)

,NUMCERTIFICADOEXT,STSESTADO,MES,ANIO,IDEERROR,NOMERROR,DSCERROR
0,00110982644000572646,ERR,6,2025,97,"Error, Dif. monto prima bruta calculado del pl...",EL CAMPO mx1 ES DIFERENTE A LA PRIMA BRUTA CAL...
1,00110318344000918290,ERR,7,2025,97,"Error, Dif. monto prima bruta calculado del pl...",EL CAMPO mx1 ES DIFERENTE A LA PRIMA BRUTA CAL...
2,00110982684000591780,ERR,9,2023,97,"Error, Dif. monto prima bruta calculado del pl...",EL CAMPO mx1 ES DIFERENTE A LA PRIMA BRUTA CAL...

In [39]:
df_Certificados1.drop(['CODIGOTEMP','IDELOTE', 'IDEDET','FECINIVIGCAN','FECFINVIGCAN','ULTIMA_FECHA_PRO','TIENE_PRO' ], axis=1, inplace=True)
df_Certificados1.head(3)

      NUMCERTIFICADOEXT ESTADO  MES  ANIO IDEERROR
0  00110002304000164476    ERR   10  2023     2046
1  00110002304000183861    ERR    2  2024     2048
2  00110002304000183861    ERR    2  2024     1153

In [40]:
df_Certificados2= df_Certificados2.rename(columns={'STSESTADO': 'ESTADO'})
df_Certificados2.head(3)

,NUMCERTIFICADOEXT,ESTADO,MES,ANIO,IDEERROR,NOMERROR,DSCERROR
0,00110982644000572646,ERR,6,2025,97,"Error, Dif. monto prima bruta calculado del pl...",EL CAMPO mx1 ES DIFERENTE A LA PRIMA BRUTA CAL...
1,00110318344000918290,ERR,7,2025,97,"Error, Dif. monto prima bruta calculado del pl...",EL CAMPO mx1 ES DIFERENTE A LA PRIMA BRUTA CAL...
2,00110982684000591780,ERR,9,2023,97,"Error, Dif. monto prima bruta calculado del pl...",EL CAMPO mx1 ES DIFERENTE A LA PRIMA BRUTA CAL...

In [ ]:
df_Certificados1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144814 entries, 0 to 144813
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   IDELOTE            144814 non-null  int64
 1   IDEDET             144814 non-null  int64
 2   NUMCERTIFICADOEXT  144814 non-null  object
 3   ESTADO             144814 non-null  object
 4   MES                144814 non-null  int64
 5   ANIO               144814 non-null  int64
 6   IDEERROR           133180 non-null  object
 7   FECINIVIGCAN       144814 non-null  datetime64[ns]
 8   TIENE_PRO          144814 non-null  int64
dtypes: datetime64[ns](1), int64(5), object(3)
memory usage: 9.9+ MB

In [42]:
df_errores = pd.read_excel('C:/data/Data Errores/DATA_ERRORES_29_agos.xlsx', sheet_name='TABLA ERROR', dtype={'CODERROR': str, 'IDEERROR': str})
df_errores.drop(['CODERROR' ], axis=1, inplace=True)

In [43]:
df_errores.head(3)

,IDEERROR,NOMERROR,DSCERROR
0,5,EL CAMPO NO DEBE TENER VALOR ALFANUMERICO,EL CAMPO mx1 NO DEBE TENER DATOS ALFANUMERICO
1,7,"Error, Valor :mx1, igual a :mx2",EL CAMPO mx1 NO ES VALIDO
2,14,EL VALOR ENVIADO ES NULO,EL CAMPO mx1 NO DEBE SER VACIO NI TENER ESPACI...

In [44]:
df_errores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   IDEERROR  29 non-null     object
 1   NOMERROR  29 non-null     object
 2   DSCERROR  29 non-null     object
dtypes: object(3)
memory usage: 828.0+ bytes

In [45]:
df_cruzado = pd.merge(df_Certificados1, df_errores, on='IDEERROR', how='left')
df_cruzado.head(3)

,NUMCERTIFICADOEXT,ESTADO,MES,ANIO,IDEERROR,NOMERROR,DSCERROR
0,00110002304000164476,ERR,10,2023,2046,Error-Fecha inicio diferente a fecha fin de ul...,FECHA DE INICIO DE VIGENCIA DEL PAGO ES DIFERE...
1,00110002304000183861,ERR,2,2024,2048,ERROR TASA,ERROR TASA
2,00110002304000183861,ERR,2,2024,1153,"Error, Alta generada se encuentra con Error Canal",EL ALTA DEL NRO. CERTIFICADO EXTERNO SE ENCUEN...

In [46]:
df_cruzado['FECHA_CARGA'] = pd.to_datetime('2025-08-29')

In [49]:
df_Certificados2['FECHA_CARGA'] = pd.to_datetime('2025-09-02')

In [11]:
df_cruzado['ANIO'].value_counts()

ANIO
2025    53767
2023    49266
2024    40259
2022      692
2021      403
2018      116
2019      107
2020      101
2016       35
2017       20
2026       19
2015       18
2014        6
2027        5
Name: count, dtype: int64

In [16]:
df_cruzado[df_cruzado['ANIO']==2026].head(3)

,IDELOTE,IDEDET,NUMCERTIFICADOEXT,ESTADO,MES,ANIO,IDEERROR,FECINIVIGCAN,TIENE_PRO,CODIGO ERROR,NOMBRE ERROR,DESCRIPCION ERROR,FECHA_CARGA
6452,1129288,667664406,00110119504000260897,ERR,2,2026,2046,2026-02-18,39,7578,Error-Fecha inicio diferente a fecha fin de ul...,FECHA DE INICIO DE VIGENCIA DEL PAGO ES DIFERE...,2025-08-29
23066,1316387,782151887,00110199704000861196,ERR,3,2026,2046,2026-03-02,12,7578,Error-Fecha inicio diferente a fecha fin de ul...,FECHA DE INICIO DE VIGENCIA DEL PAGO ES DIFERE...,2025-08-29
54500,1295401,756820194,00110284764000984095,ERR,1,2026,2046,2026-01-05,14,7578,Error-Fecha inicio diferente a fecha fin de ul...,FECHA DE INICIO DE VIGENCIA DEL PAGO ES DIFERE...,2025-08-29

In [47]:
df_cruzado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144814 entries, 0 to 144813
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   NUMCERTIFICADOEXT  144814 non-null  object
 1   ESTADO             144814 non-null  object
 2   MES                144814 non-null  int64
 3   ANIO               144814 non-null  int64
 4   IDEERROR           133180 non-null  object
 5   NOMERROR           133133 non-null  object
 6   DSCERROR           133133 non-null  object
 7   FECHA_CARGA        144814 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 8.8+ MB

In [51]:
df_Certificados2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87122 entries, 0 to 87121
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   NUMCERTIFICADOEXT  87122 non-null  object
 1   ESTADO             87122 non-null  object
 2   MES                87122 non-null  int64
 3   ANIO               87122 non-null  int64
 4   IDEERROR           86252 non-null  object
 5   NOMERROR           86252 non-null  object
 6   DSCERROR           86252 non-null  object
 7   FECHA_CARGA        87122 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 5.3+ MB

In [48]:
df_cruzado.to_excel('C:/data/Data Errores/data_errores_29_ago.xlsx', index=False)

In [50]:
df_Certificados2.to_excel('C:/data/Data Errores/data_errores_02_sep.xlsx', index=False)

In [52]:
df_union = pd.concat([df_cruzado, df_Certificados2], ignore_index=True)

In [53]:
df_union.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231936 entries, 0 to 231935
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   NUMCERTIFICADOEXT  231936 non-null  object
 1   ESTADO             231936 non-null  object
 2   MES                231936 non-null  int64
 3   ANIO               231936 non-null  int64
 4   IDEERROR           219432 non-null  object
 5   NOMERROR           219385 non-null  object
 6   DSCERROR           219385 non-null  object
 7   FECHA_CARGA        231936 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 14.2+ MB

In [54]:
df_union.to_excel('C:/data/Data Errores/data_errores_Completo.xlsx', index=False)