In [1]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import os
import numpy as np
pd.set_option('display.max_columns', None)

In [85]:
df_conticasa= pd.read_excel('C:/data/ERRORES-CONTICASA/ERRORES-RESPUESTA TICKET/Consolidado_errores_conticasa_enero25-julio25.xlsx', 
                             sheet_name='Hoja1', dtype={'CODPROD':str, 'NUMPOL':str,'NUMCERT':str,'NRO_CERT_BANCO': str, 'CANTPROR': str} )

In [86]:
df_conticasa.head(3)

,MES,CODPROD,NUMPOL,NUMCERT,NRO_CERT_BANCO,CANTPROR,INDICADOR,OBSERVACION
0,2025-01-01,1304,501486,35,00110196354000274731,2,-1,ORA-20100: PR_POLIZA.ACTIVAR: ORA-20100: PR_PO...
1,2025-01-01,1304,501490,161,00110482794000320444,2,-1,ORA-20100: PR_POLIZA.ACTIVAR: ORA-20100: PR_PO...
2,2025-01-01,1304,501490,162,00110320964000396317,2,-1,ORA-20100: PR_POLIZA.ACTIVAR: ORA-20100: PR_PO...

In [87]:
df_conticasa= df_conticasa.fillna({'CODPROD':'', 'NUMPOL': '', 'NUMCERT': '', 'NRO_CERT_BANCO': '', 'CANTPROR': '0'})

In [72]:
df_conticasa['NRO_CERT_BANCO'].isna().sum()

np.int64(0)

In [88]:
df_conticasa['POLIZA_Y_CERTIFICADO']= df_conticasa['CODPROD'] + '-'+ df_conticasa['NUMPOL'] + '-' + df_conticasa['NUMCERT']

In [89]:

def separar_Observacion(observacion, indicador):
    resultado = []
    if indicador == -1:
        partes = observacion.split(':')
        nro_partes= len(partes)
        if nro_partes == 1:
            resultado= [partes[0],"",""]
        elif nro_partes == 2:
            resultado= [partes[1],"",""]
        elif nro_partes == 4:    
            resultado = [partes[1], "", partes[3]]
        else:
            resultado = [partes[1], partes[3], ':'.join(partes[4:])]
    else:
        partes = observacion.split('|')
        if len(partes) == 1:
            resultado = [partes[0], "", ""]
        else:
            resultado = [partes[0], partes[1], ""]
    return resultado

In [90]:
# Aplicar la función y expandir en columnas
df_conticasa[['DESCRIPCION1', 'DESCRIPCION2', 'DATALLE']] = df_conticasa.apply(lambda row: pd.Series(separar_Observacion(row['OBSERVACION'], row['INDICADOR'])), axis=1)

In [91]:
df_conticasa.head(3)

,MES,CODPROD,NUMPOL,NUMCERT,NRO_CERT_BANCO,CANTPROR,INDICADOR,OBSERVACION,POLIZA_Y_CERTIFICADO,DESCRIPCION1,DESCRIPCION2,DATALLE
0,2025-01-01,1304,501486,35,00110196354000274731,2,-1,ORA-20100: PR_POLIZA.ACTIVAR: ORA-20100: PR_PO...,1304-501486-35,PR_POLIZA.ACTIVAR,PR_POLIZA.ACTIVAR,Existen certificados que no tienen configurad...
1,2025-01-01,1304,501490,161,00110482794000320444,2,-1,ORA-20100: PR_POLIZA.ACTIVAR: ORA-20100: PR_PO...,1304-501490-161,PR_POLIZA.ACTIVAR,PR_POLIZA.ACTIVAR,Existen certificados que no tienen configurad...
2,2025-01-01,1304,501490,162,00110320964000396317,2,-1,ORA-20100: PR_POLIZA.ACTIVAR: ORA-20100: PR_PO...,1304-501490-162,PR_POLIZA.ACTIVAR,PR_POLIZA.ACTIVAR,Existen certificados que no tienen configurad...

In [83]:
df_conticasa['CANTPROR'].value_counts()

CANTPROR
0    3506
1    1179
2      27
Name: count, dtype: int64

In [84]:
df_conticasa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4712 entries, 0 to 4711
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MES             4712 non-null   datetime64[ns]
 1   CODPROD         4712 non-null   object
 2   NUMPOL          4712 non-null   object
 3   NUMCERT         4712 non-null   object
 4   NRO_CERT_BANCO  4712 non-null   object
 5   CANTPROR        4712 non-null   object
 6   INDICADOR       4712 non-null   int64
 7   OBSERVACION     4712 non-null   object
 8   DESCRIPCION1    4712 non-null   object
 9   DESCRIPCION2    4712 non-null   object
 10  DATALLE         4712 non-null   object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 405.1+ KB