In [1]:
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
import os
import numpy as np
pd.set_option('display.max_columns', None)

In [87]:
df_errores1= pd.read_excel('C:/data/TABLA_ERRORES_COMPLETO.xlsx', sheet_name='Hoja1', dtype={'IDEERROR': str, 'CODERROR': str})
df_errores2 = pd.read_excel('C:/data/tabla_errores_sergio.xlsx', sheet_name='Sheet1', dtype={'IDEERROR': str, 'CODIGO_ERROR': str})

In [88]:
df_errores1 = df_errores1[df_errores1.columns[:4]]
df_errores1= df_errores1.rename(columns={'CODERROR': 'CODIGO_ERROR','NOMERROR':'NOMBRE_ERROR_SAS','DSCERROR':'DESC_ERROR_SAS'})
df_errores1['NOMBRE_ERROR_SAS']= df_errores1['NOMBRE_ERROR_SAS'].str.upper()
df_errores1['DESC_ERROR_SAS']= df_errores1['DESC_ERROR_SAS'].str.upper()
df_errores1['IDEERROR'] = df_errores1['IDEERROR'].apply(lambda x: str(int(x)).zfill(4) if pd.notnull(x) else "")
df_errores1['CODIGO_ERROR'] = df_errores1['CODIGO_ERROR'].apply(lambda x: str(int(x)).zfill(4) if pd.notnull(x) else "")

In [89]:
df_errores1.head(3)

,IDEERROR,CODIGO_ERROR,NOMBRE_ERROR_SAS,DESC_ERROR_SAS
0,,,NaN,NaN
1,0041,0026,"NO EXISTE CONFIGURADO REFERENCIA EXTERNA, MODE...",EL CAMPO MX1 NO ES VALIDO
2,0042,0027,"NO EXISTE CONFIGURADO REFERENCIA EXTERNA, USO ...",EL CAMPO MX1 NO ES VALIDO

In [90]:
df_errores1[df_errores1['IDEERROR']==''].head(3)

  IDEERROR CODIGO_ERROR NOMBRE_ERROR_SAS DESC_ERROR_SAS
0                                    NaN            NaN

In [91]:
df_errores1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1447 entries, 0 to 1446
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDEERROR          1447 non-null   object
 1   CODIGO_ERROR      1447 non-null   object
 2   NOMBRE_ERROR_SAS  1181 non-null   object
 3   DESC_ERROR_SAS    1446 non-null   object
dtypes: object(4)
memory usage: 45.3+ KB

In [92]:
df_errores2= df_errores2.fillna({'IDEERROR':'', 'CODIGO_ERROR':''})
df_errores2.head(3)

,IDEERROR,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,0974,1068,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,YA EXISTE UN PAGO CON LA MISMA FECHA DE INICIO...,CONFIGURACION SAS,ANULAR MASIVAS
1,0005,0003,ERROR EN CARGA DE TRAMA,ERROR EN CARGA DE TRAMA,ANALISIS EMISOR,NaN
2,1158,1155,TRAMA REPETIDA O DUPLICADA,TRAMA REPETIDA O DUPLICADA,CONFIGURACION SAS,ANULAR MASIVAS

In [93]:
df_errores2[df_errores2['IDEERROR']==''].head(3)

,IDEERROR,CODIGO_ERROR,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
12,,,ERROR EN CARGA DE TRAMA,NI ÉXITO NI ERROR,ANALISIS EMISOR,NaN

In [94]:
df_errores2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   IDEERROR           54 non-null     object
 1   CODIGO_ERROR       54 non-null     object
 2   DESCRIPCION_ERROR  54 non-null     object
 3   DETALLE            54 non-null     object
 4   SOLUCION           54 non-null     object
 5   SOLUCION_2         19 non-null     object
dtypes: object(6)
memory usage: 2.7+ KB

In [95]:
df_errores1= df_errores1.merge(df_errores2, on='IDEERROR', how='left')

In [96]:
df_errores1= df_errores1.rename(columns={'CODIGO_ERROR_x': 'CODIGO_ERROR'})
df_errores1.drop(columns=['CODIGO_ERROR_y'], inplace=True)

In [97]:
df_errores1.head(3)

,IDEERROR,CODIGO_ERROR,NOMBRE_ERROR_SAS,DESC_ERROR_SAS,DESCRIPCION_ERROR,DETALLE,SOLUCION,SOLUCION_2
0,,,NaN,NaN,ERROR EN CARGA DE TRAMA,NI ÉXITO NI ERROR,ANALISIS EMISOR,NaN
1,0041,0026,"NO EXISTE CONFIGURADO REFERENCIA EXTERNA, MODE...",EL CAMPO MX1 NO ES VALIDO,NaN,NaN,NaN,NaN
2,0042,0027,"NO EXISTE CONFIGURADO REFERENCIA EXTERNA, USO ...",EL CAMPO MX1 NO ES VALIDO,NaN,NaN,NaN,NaN

In [98]:
df_errores1.to_excel('C:/data/Tabla_Errores_SAS.xlsx', index=False)