In [2]:
import pandas as pd
import os

In [3]:
espacios_col = [(0, 3), (3, 23), (23, 43), (43,45), (45, 48), (48, 49), (49, 79), (79, 109), (109, 139),   
                (139, 140), (140, 141), (141, 149), (149, 150), (150, 160), (160, 210), (210, 235),   
                (235, 260), (260, 290), (290, 298), (298, 306), (306, 336), (336, 338), (338, 343),   
                (343, 346), (346, 347), (347, 350), (350, 353), (353, 355), (355, 358), (358, 361), 
                (361, 368), (368, 376), (376, 384), (384, 392), (392, 396), (396, 411), (411, 426),   
                (426, 427), (427, 429), (429, 430), (430, 431), (431, 432), (432, 442), (442, 449),   
                (449, 522), (522, 524), (524, 527), (527, 530), (530, 540), (540, 550), (550,565),
                (565, 635), (635, 637), (637, 639), (639,641)   
                ]

In [4]:
column_names = ["Tipo de seguro", "Certificado", "Numero Interno Del Canal", "Tipo de Registro", "Moneda", 
                "Tipo de Movimiento", "Apellido Paterno", "Apellido Materno", "Nombres", "Sexo", "Estado Civil", 
                "Fecha de Nacimiento", "Tipo de Documento de Identidad", "Numero de Documento de Identidad", 
                "Dirección Domiciliaria", "Referencia", "Referencia2", "Urbanización", "Mz/Lte/Nro", "Apto/Int", 
                "Distrito", "Departamento", "Código Postal", "País", "Periodo de pago", "Prefijo Calle,Av,Jr", 
                "Prefijo 2", "Provincia", "Distrito2", "Prefijo Teléfono", "Numero Teléfono", "Fecha de Afiliación", 
                "Fecha de inicio del seguro", "Fecha fin del seguro", "Plazo del seguro", "Monto Asegurado", "Prima", 
                "Período de Gracia", "Código de Beneficiario", "Clase de Prima", "Tipo de Titular", "Mayor a 65 Años", 
                "Tasa sin Recargo", "% de recargo", "Filler", "Tiempo de Periodo de Gracia", "Tipos de Endoso", 
                "Tipos de Extorno", "Tipo de cambio", "Póliza", "Sumatoria de Capital en Cúmulo", "Correo electrónico", 
                "Plan de crédito", "Planes Tipo Desgravamen", "Planes de Seguro (o Modalidad)"
                ]

In [9]:

pd.set_option('display.max_columns', None)

In [6]:
df = pd.read_fwf("C:/data/RED030325_0403.TXT", colspecs=espacios_col, names=column_names, encoding='latin1')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 55 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Tipo de seguro                    70609 non-null  int64
 1   Certificado                       70609 non-null  int64
 2   Numero Interno Del Canal          70609 non-null  object
 3   Tipo de Registro                  70609 non-null  int64
 4   Moneda                            70609 non-null  object
 5   Tipo de Movimiento                70609 non-null  object
 6   Apellido Paterno                  70029 non-null  object
 7   Apellido Materno                  68247 non-null  object
 8   Nombres                           50733 non-null  object
 9   Sexo                              50726 non-null  object
 10  Estado Civil                      50726 non-null  object
 11  Fecha de Nacimiento               53473 non-null  object
 12  Tipo de Documento de Identidad    53471 non-null  object
 13  Numero de Documento de Identidad  53471 non-null  object
 14  Dirección Domiciliaria            53438 non-null  object
 15  Referencia                        43057 non-null  object
 16  Referencia2                       6524 non-null   object
 17  Urbanización                      52369 non-null  object
 18  Mz/Lte/Nro                        53322 non-null  object
 19  Apto/Int                          30089 non-null  object
 20  Distrito                          53078 non-null  object
 21  Departamento                      53451 non-null  float64
 22  Código Postal                     41069 non-null  object
 23  País                              53461 non-null  object
 24  Periodo de pago                   49398 non-null  object
 25  Prefijo Calle,Av,Jr               50202 non-null  object
 26  Prefijo 2                         30942 non-null  object
 27  Provincia                         53451 non-null  float64
 28  Distrito2                         53451 non-null  float64
 29  Prefijo Teléfono                  52722 non-null  float64
 30  Numero Teléfono                   52722 non-null  float64
 31  Fecha de Afiliación               53617 non-null  float64
 32  Fecha de inicio del seguro        53651 non-null  object
 33  Fecha fin del seguro              54045 non-null  float64
 34  Plazo del seguro                  53428 non-null  object
 35  Monto Asegurado                   54045 non-null  object
 36  Prima                             54045 non-null  object
 37  Período de Gracia                 20304 non-null  object
 38  Código de Beneficiario            44755 non-null  float64
 39  Clase de Prima                    61113 non-null  object
 40  Tipo de Titular                   61006 non-null  object
 41  Mayor a 65 Años                   25809 non-null  object
 42  Tasa sin Recargo                  50166 non-null  object
 43  % de recargo                      48427 non-null  object
 44  Filler                            45227 non-null  object
 45  Tiempo de Periodo de Gracia       1700 non-null   object
 46  Tipos de Endoso                   533 non-null    object
 47  Tipos de Extorno                  3915 non-null   object
 48  Tipo de cambio                    15363 non-null  object
 49  Póliza                            3784 non-null   object
 50  Sumatoria de Capital en Cúmulo    17714 non-null  object
 51  Correo electrónico                6225 non-null   object
 52  Plan de crédito                   11269 non-null  object
 53  Planes Tipo Desgravamen           16863 non-null  object
 54  Planes de Seguro (o Modalidad)    35884 non-null  float64
dtypes: float64(9), int64(3), object(43)
memory usage: 29.6+ MB

In [7]:
filas_con_especiales = df[df["Urbanización"].str.contains(r'[^\w\s.,-]', na=False)]
filas_con_especiales['Urbanización'].head()

152    MARTINEZ DE COMPA#ON MZ G LT 7
199                        LA CAMPI#A
264          LAS COLINAS #A#A CHOSICA
272                       LOS VI#EDOS
312          JUAN INGUNZA V ( VIPOL )
Name: Urbanización, dtype: object

In [8]:
df[['Fecha de Afiliación', 'Fecha de inicio del seguro', 'Fecha fin del seguro']].head(5)

   Fecha de Afiliación Fecha de inicio del seguro  Fecha fin del seguro
0           20250303.0                   20250301            20250401.0
1           20250303.0                   20250302            20250402.0
2           20250303.0                   20250301            20250401.0
3           20250303.0                   20250301            20250401.0
4           20250303.0                   20250301            20250401.0

In [8]:
df2= df[120:140]  # Displaying a sample of the DataFrame to verify the data

In [10]:
df2.head(3)  # Displaying the first three rows of the sample DataFrame

,Tipo de seguro,Certificado,Numero Interno Del Canal,Tipo de Registro,Moneda,Tipo de Movimiento,Apellido Paterno,Apellido Materno,Nombres,Sexo,Estado Civil,Fecha de Nacimiento,Tipo de Documento de Identidad,Numero de Documento de Identidad,Dirección Domiciliaria,Referencia,Referencia2,Urbanización,Mz/Lte/Nro,Apto/Int,Distrito,Departamento,Código Postal,País,Periodo de pago,"Prefijo Calle,Av,Jr",Prefijo 2,Provincia,Distrito2,Prefijo Teléfono,Numero Teléfono,Fecha de Afiliación,Fecha de inicio del seguro,Fecha fin del seguro,Plazo del seguro,Monto Asegurado,Prima,Período de Gracia,Código de Beneficiario,Clase de Prima,Tipo de Titular,Mayor a 65 Años,Tasa sin Recargo,% de recargo,Filler,Tiempo de Periodo de Gracia,Tipos de Endoso,Tipos de Extorno,Tipo de cambio,Póliza,Sumatoria de Capital en Cúmulo,Correo electrónico,Plan de crédito,Planes Tipo Desgravamen,Planes de Seguro (o Modalidad)
120,803,110465234001858380,0465,1,PEN,4,ARATEA,RAMOS,MARCOS ANTONIO,M,S,19780406,L,42773668,URB VILLA MARIA DEL TRIUNFO,POR LA PLAZA,NaN,NO APLICA,MZ F,LT 9,TACNA,23.0,P0001,PER,M,CAL,NaN,1.0,9.0,95.0,2360935.0,20250303.0,20250301,20250401.0,000{,00000001500000{,00000000000384{,1,3.0,0,0,0,0270876000,0015000,00{000000000384{0000{0000{0000{001101740202003...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0
121,803,110465204001859220,0465,1,PEN,4,GIL,MILLER,WENDY JANE,F,C,19670801,L,09396144,HUANCAVELICA,CC,NaN,SANTA PATRICIA,375,301,LA MOLINA,1.0,L0012,PER,M,CAL,URB,1.0,12.0,95.0,1045583.0,20250303.0,20250302,20250402.0,000{,00000001500000{,00000000000384{,1,3.0,0,0,0,0270917000,0015000,00{000000000384{0000{0000{0000{001100577002185...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0
122,803,110465244001859379,0465,1,PEN,4,GOMEZ,SEGURA,LUIS FRANCISCO,M,C,19691109,L,16687296,URB MONTERRICO 4TA ETAPA EDIFCIO RESIDENCIAL,A DOS CUADROS PARQU,NaN,CHICLAYO,MZ H,LT 21,CHICLAYO,15.0,P0001,PER,M,AV.,NaN,1.0,1.0,97.0,8013500.0,20250303.0,20250302,20250402.0,000{,00000001500000{,00000000000384{,1,3.0,0,0,0,0270925000,0015000,00{000000000384{0000{0000{0000{001102854902008...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0

In [ ]:
df2.to_csv("C:/data/RED030325_0403_sample.csv", index=False, encoding='latin1')  # Saving the sample to a CSV file

-----

In [ ]:
# Lista para guardar los DataFrames
dataframes = []
ruta = 'c:/nps pt'  
# Recorrer todos los archivos en la carpeta
for archivo in os.listdir(ruta):
    if archivo.endswith('.xlsx') or archivo.endswith('.xls'):
        df = pd.read_excel(os.path.join(ruta, archivo))
        dataframes.append(df)

# Unir todos los DataFrames en uno solo
df_combinado = pd.concat(dataframes, ignore_index=True)

# Guardar el resultado en un nuevo archivo Excel
df_combinado.to_excel('archivo_combinado.xlsx', index=False)